"""
Feedback Automation Configuration

This file centralizes all configuration for the streamlined feedback workflow.
Edit the parameters below to control how feedback updates are generated automatically.
"""

# =============================================================================
# BASE DMD PROFILE SOURCE (choose ONE option)
# =============================================================================

# Option 1: Load from a previous shot's h5 file
USE_H5_PROFILE = True

# If USE_H5_PROFILE is True, specify the shot here:
H5_SHOT_YEAR = 2026
H5_SHOT_MONTH = 4
H5_SHOT_DAY = 9
H5_SHOT_SEQUENCE = 27
H5_SHOT_ITERATION = 0
H5_SHOT_REPETITION = 14

# Option 2: Load from a txt file (set USE_H5_PROFILE to False)
PROFILE_TXT_FILE = 'dmd_profile_20260331_103346.txt'  # Relative to DMD folder or absolute path

# =============================================================================
# NEW SIGMOID PROFILE LOCATION
# =============================================================================

# Path to the new sigmoid profile generated by waterfall analysis
# Usually: /path/to/waterfall/sigmoid_center_interpolation.txt
NEW_SIGMOID_PATH = '/home/rick/labscript-suite/userlib/analysislib/analysislib_v2/waterfall/sigmoid_center_interpolation.txt'

# =============================================================================
# OUTPUT DIRECTORIES
# =============================================================================

# Subfolder inside DMD folder to store all magnetization feedback profiles
# Will be auto-created if it doesn't exist
# All sigmoid files will be saved here: magnetization_feedback/sigmoid_*.txt
MAGNETIZATION_FEEDBACK_FOLDER = 'magnetization_feedback'

# Legacy setting (kept for backward compatibility)
# Where to save the updated sigmoid profiles in the DMD folder
# They will be named: sigmoid_center_interpolation_update_N.txt
DMD_PROFILES_FOLDER = None  # Set to None to use DMD folder, or set a custom path

# =============================================================================
# GAUSSIAN SMOOTHING PARAMETERS
# =============================================================================

# Default Gaussian blur sigma for error profiles (in pixels)
# Used for new profiles added via auto_feedback_update.py
DEFAULT_SMOOTHING_SIGMA = 2.0

# =============================================================================
# FEEDBACK GAINS (KP)
# =============================================================================

# Proportional gain for the new sigmoid profile
# This controls how strongly the new profile is applied to the DMD
# Used for new profiles added via auto_feedback_update.py
NEW_PROFILE_KP = 0.8

# =============================================================================
# FEEDBACK REGION AND WALLS
# =============================================================================

# Import from main feedback_config
from feedback_config import WALL_TYPE, X_CENTER, FEEDBACK_WIDTH, SOFT_WALL_WIDTH

# =============================================================================
# PLOT SETTINGS
# =============================================================================

# Auto-update plot_sigmoid_txt.py configuration?
AUTO_UPDATE_PLOT_CONFIG = True

# Label for the new profile in the plot
NEW_PROFILE_PLOT_LABEL = 'New'

# Bias field offset and conversion factors
BIAS_FIELD_OFFSET_MG = 129.8
MG_TO_HZ = 2.1e3
MG_TO_UG = 1e3

# Region (in x [um]) used for RMS calculation in plot
REGION_START_UM = 950
REGION_END_UM = 1150

# =============================================================================
# DMD SERVER
# =============================================================================

# Import from main feedback_config
from feedback_config import DMD_SERVER_IP, DMD_SERVER_PORT

# Should auto_feedback_update load the profile to the DMD server?
LOAD_TO_DMD = True  # Set to False to skip, or use --no-server flag to disable

# =============================================================================
# ADVANCED OPTIONS
# =============================================================================

# Verbosity level (0=quiet, 1=normal, 2=verbose)
VERBOSITY = 1

# Create backups of modified files?
CREATE_BACKUPS = True

# Automatically show plot after update?
SHOW_PLOT = False
