#!/usr/bin/env python3
"""
Interactive KZ Article Analysis Script

Workflow:
1. Load config files (main config, camera settings, defect config)
2. For each dataset:
   a. Load raw data from specified day/sequences
   b. Show 5 random profiles from different detunings (KZ_det_scan variation)
   c. Ask user to tune affine_correction, x_min_integration, x_max_integration
   d. Run waterfall_v2 analysis with KZ_det_scan mode
   e. Show domain wall plots
   f. Ask user to set domain_balance_fit_window
   g. Ask for permission to continue to next dataset
3. Save iteration folder with all configs and analysis results

Usage:
    python run_kz_article_analysis.py /path/to/config.yaml [--iteration N]
"""

import sys
import os
import yaml
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from pathlib import Path
import logging
import getpass

sys.path.insert(0, '/home/rick/labscript-suite/userlib/analysislib/analysislib_v2')
sys.path.insert(0, '/home/rick/labscript-suite/userlib/analysislib/analysislib_v2/general_lib')

from multishot_lib import get_day_data, get_and_filter_shots
from waterfall_v2.waterfall_lib import waterfall_plot

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class KZArticleAnalyzer:
    """Interactive analyzer for KZ article datasets"""
    
    def __init__(self, config_path, camera_settings_path, defect_config_path, iteration=None):
        """
        Initialize analyzer with config files.
        
        Parameters
        ----------
        config_path : str
            Path to main config.yaml
        camera_settings_path : str
            Path to camera_settings.yaml
        defect_config_path : str
            Path to defect_config.yaml
        iteration : int, optional
            Specific iteration to run (default: auto-increment from today's count)
        """
        self.config = self._load_yaml(config_path)
        self.camera_settings = self._load_yaml(camera_settings_path)
        self.defect_config = self._load_yaml(defect_config_path)
        
        self.config_path = config_path
        self.camera_settings_path = camera_settings_path
        self.defect_config_path = defect_config_path
        
        # Determine iteration number
        if iteration is None:
            self.iteration = self._get_next_iteration()
        else:
            self.iteration = iteration
        
        # Setup results directory
        self.results_dir = self._setup_results_dir()
        logger.info(f"Results will be saved to: {self.results_dir}")
    
    @staticmethod
    def _load_yaml(path):
        """Load YAML config file"""
        with open(path, 'r') as f:
            return yaml.safe_load(f)
    
    def _get_next_iteration(self):
        """Determine next iteration number for today"""
        results_base = Path(__file__).parent / "results"
        today = datetime.now()
        year_month_day = today.strftime('%Y/%m/%d')
        day_dir = results_base / year_month_day
        
        if not day_dir.exists():
            return 1
        
        # Find highest iteration number
        max_iter = 0
        for folder in day_dir.iterdir():
            if folder.is_dir() and folder.name.startswith('iteration_'):
                try:
                    iter_num = int(folder.name.split('_')[1])
                    max_iter = max(max_iter, iter_num)
                except (ValueError, IndexError):
                    pass
        
        return max_iter + 1
    
    def _setup_results_dir(self):
        """Setup results directory with year/month/day/iteration_N structure"""
        results_base = Path(__file__).parent / "results"
        today = datetime.now()
        year_month_day = today.strftime('%Y/%m/%d')
        iteration_dir = results_base / year_month_day / f"iteration_{self.iteration}"
        
        iteration_dir.mkdir(parents=True, exist_ok=True)
        return iteration_dir
    
    def show_sample_profiles(self, dataset_config):
        """
        Show 5 random m1/m2 profiles from different detunings.
        
        For KZ_det_scan, detuning varies between shots, so we select
        shots with different KZ_det_scan values.
        """
        date_cfg = dataset_config['date']
        seqs = dataset_config['sequences']
        camera_name = self.camera_settings['camera_settings']['camera_name']
        
        # Load PREPROCESSED data from data_reanalyzed (generated by run_show_ODs_batch.py)
        hdf_config = {
            'raw_or_processed': 'processed',  # Load from data_reanalyzed/ not raw NAS
            'year': date_cfg['year'],
            'month': date_cfg['month'],
            'day': date_cfg['day'],
        }
        
        # Use get_and_filter_shots which applies SHOT_FILTER_CONFIG from config
        # This will use filtering thresholds from multishot_lib config
        try:
            df_filtered = get_and_filter_shots(hdf_config, camera_name, seqs=seqs)
            logger.info(f"Successfully loaded shots using get_and_filter_shots")
        except Exception as e:
            logger.error(f"Error loading data: {e}", exc_info=True)
            logger.error(f"Could not load or filter data for {date_cfg}")
            return None, None
        
        if df_filtered is None or df_filtered.empty:
            logger.error(f"Could not load or filter data for {date_cfg}")
            return None, None
        
        logger.info(f"Loaded {len(df_filtered)} shots after quality filtering")
        logger.info(f"Filtered DataFrame shape: {df_filtered.shape}")
        logger.info(f"Filtered DataFrame columns (first 10): {df_filtered.columns[:10].tolist()}")
        
        if len(df_filtered) < 5:
            logger.warning(f"Only {len(df_filtered)} shots after filtering, using all")
            sample_indices = list(range(len(df_filtered)))
        else:
            # Select 5 random shots with good spread
            sample_indices = np.random.choice(len(df_filtered), size=5, replace=False)
            sample_indices = sorted(sample_indices)
        
        # Extract m1_1d and m2_1d data
        m1_col = (self.camera_settings['camera_settings']['data_origin'], 'm1_1d')
        m2_col = (self.camera_settings['camera_settings']['data_origin'], 'm2_1d')
        
        # Check if columns exist
        if m1_col not in df_filtered.columns or m2_col not in df_filtered.columns:
            logger.error(f"Expected columns {m1_col} and {m2_col} not found in data")
            logger.error(f"Available columns: {df_filtered.columns.tolist()}")
            return None, None
        
        fig, axes = plt.subplots(5, 2, figsize=(14, 12))
        fig.suptitle(f"Sample Profiles - Dataset {dataset_config['dataset_id']}\n"
                     f"({date_cfg['year']}-{date_cfg['month']:02d}-{date_cfg['day']:02d})",
                     fontsize=14, fontweight='bold')
        
        for i, idx in enumerate(sample_indices):
            shot = df_filtered.iloc[idx]
            m1_data = np.array(shot[m1_col])
            m2_data = np.array(shot[m2_col])
            
            # Debug: Check data shapes
            if i == 0:
                logger.info(f"m1_data type: {type(shot[m1_col])}, shape: {m1_data.shape}, dtype: {m1_data.dtype}")
                logger.info(f"m2_data type: {type(shot[m2_col])}, shape: {m2_data.shape}, dtype: {m2_data.dtype}")
                logger.info(f"m1_data value: {m1_data}")
                logger.info(f"m2_data value: {m2_data}")
            
            x_pixels = np.arange(len(m1_data))
            
            # Plot m1
            axes[i, 0].plot(x_pixels, m1_data, 'b-', linewidth=1.5)
            axes[i, 0].set_ylabel(f'Shot {idx}\nm1', fontsize=9)
            axes[i, 0].grid(True, alpha=0.3)
            
            # Plot m2
            axes[i, 1].plot(x_pixels, m2_data, 'r-', linewidth=1.5)
            axes[i, 1].set_ylabel(f'Shot {idx}\nm2', fontsize=9)
            axes[i, 1].grid(True, alpha=0.3)
        
        axes[-1, 0].set_xlabel('Pixel position')
        axes[-1, 1].set_xlabel('Pixel position')
        plt.tight_layout()
        
        return fig, df_filtered
    
    def prompt_affine_correction(self, current_values):
        """Prompt user to adjust affine correction coefficients"""
        print("\n" + "="*80)
        print("AFFINE CORRECTION COEFFICIENTS")
        print("="*80)
        print("Current values:")
        for key, val in current_values.items():
            print(f"  {key}: {val}")
        print("\nAffine correction formula:")
        print("  n1D_m1' = a1*n1D_m1 + b1*n1D_m2 + c1")
        print("  n1D_m2' = a2*n1D_m2 + b2*n1D_m1 + c2")
        print("\nEnter new values (or press Enter to keep current):")
        
        updated = dict(current_values)
        for key in ['a1', 'b1', 'c1', 'a2', 'b2', 'c2']:
            while True:
                try:
                    user_input = input(f"  {key} [{current_values[key]}]: ").strip()
                    if user_input:
                        updated[key] = float(user_input)
                    break
                except ValueError:
                    print(f"  Invalid input. Please enter a number.")
        
        return updated
    
    def prompt_integration_limits(self, current_xmin, current_xmax):
        """Prompt user to adjust integration limits"""
        print("\n" + "="*80)
        print("INTEGRATION LIMITS (micrometers)")
        print("="*80)
        print(f"Current x_min: {current_xmin} μm")
        print(f"Current x_max: {current_xmax} μm")
        
        while True:
            try:
                x_min = input(f"Enter x_min [{current_xmin}]: ").strip()
                if x_min:
                    x_min = float(x_min)
                else:
                    x_min = current_xmin
                break
            except ValueError:
                print("Invalid input. Please enter a number.")
        
        while True:
            try:
                x_max = input(f"Enter x_max [{current_xmax}]: ").strip()
                if x_max:
                    x_max = float(x_max)
                else:
                    x_max = current_xmax
                break
            except ValueError:
                print("Invalid input. Please enter a number.")
        
        return x_min, x_max
    
    def prompt_domain_fit_window(self, current_window):
        """Prompt user to adjust domain wall fit window"""
        print("\n" + "="*80)
        print("DOMAIN WALL FIT WINDOW (micrometers)")
        print("="*80)
        print(f"Current window: {current_window}")
        print("Adjust the x range for linear fit of domain wall position vs time")
        
        while True:
            try:
                x_min = input(f"Enter x_min for fit [{current_window[0]}]: ").strip()
                if x_min:
                    x_min = float(x_min)
                else:
                    x_min = current_window[0]
                break
            except ValueError:
                print("Invalid input. Please enter a number.")
        
        while True:
            try:
                x_max = input(f"Enter x_max for fit [{current_window[1]}]: ").strip()
                if x_max:
                    x_max = float(x_max)
                else:
                    x_max = current_window[1]
                break
            except ValueError:
                print("Invalid input. Please enter a number.")
        
        return [x_min, x_max]
    
    def _prompt_preprocessing_workflow(self, dataset_config):
        """
        For the first dataset, prompt user to run preprocessing if needed.
        
        Preprocessing is the PREREQUISITE: run_show_ODs_batch.py must generate
        consolidated HDF files before article analysis can load the data.
        """
        date_cfg = dataset_config['date']
        date_str = f"{date_cfg['year']}-{date_cfg['month']:02d}-{date_cfg['day']:02d}"
        seqs = dataset_config['sequences']
        
        print("\n" + "="*80)
        print("PREPROCESSING REQUIRED")
        print("="*80)
        print(f"\nBefore analyzing dataset {dataset_config['dataset_id']} ({date_str}),")
        print("you must first preprocess raw HDF5 files using run_show_ODs_batch.py")
        print(f"\nDataset will use sequences: {seqs}")
        print("\n" + "="*80)
        
        # Auto-run preprocessing (don't prompt for input)
        try:
            # Import and run preprocessing
            sys.path.insert(0, '/home/rick/labscript-suite/userlib/analysislib/analysislib_v2')
            from run_show_ODs_batch import run_analysis
            
            print("\n" + "="*80)
            print("RUNNING PREPROCESSING")
            print("="*80)
            success = run_analysis(
                year=date_cfg['year'],
                month=date_cfg['month'],
                day=date_cfg['day'],
                sequences=seqs,
                verbose=True
            )
            
            if success:
                print("\n✓ Preprocessing complete! Continuing analysis...")
            else:
                print("\n✗ Preprocessing failed. Please check your data and try again.")
                sys.exit(1)
        except Exception as e:
            print(f"\n✗ Error running preprocessing: {e}")
            print("You may need to run it manually:")
            print(f"  cd /home/rick/labscript-suite/userlib/analysislib/analysislib_v2")
            print(f"  python run_show_ODs_batch.py")
            sys.exit(1)
    
    def run_analysis(self):
        """Run analysis on all datasets"""
        logger.info(f"\n{'='*80}")
        logger.info(f"KZ ARTICLE ANALYSIS - Iteration {self.iteration}")
        logger.info(f"{'='*80}\n")
        
        dataset_results = {}
        
        for dataset_idx, dataset_config in enumerate(self.config['datasets']):
            dataset_id = dataset_config['dataset_id']
            logger.info(f"\n{'='*80}")
            logger.info(f"DATASET: {dataset_id}")
            logger.info(f"{'='*80}")
            
            # For first dataset, prompt to preprocess if needed
            if dataset_idx == 0:
                self._prompt_preprocessing_workflow(dataset_config)
            
            # Step 1: Show sample profiles
            logger.info("Step 1: Showing sample profiles for affine coefficient tuning...")
            result = self.show_sample_profiles(dataset_config)
            
            if result[0] is None:
                logger.error(f"Skipping {dataset_id}")
                continue
            
            fig, df_filtered = result
            
            plt.show(block=False)
            
            # Step 2: Prompt for affine correction
            logger.info("\nStep 2: Adjust affine correction coefficients")
            affine = self.prompt_affine_correction(dataset_config['affine_correction'])
            dataset_config['affine_correction'] = affine
            plt.close(fig)
            
            # Step 3: Prompt for integration limits
            logger.info("\nStep 3: Adjust integration limits")
            x_min, x_max = self.prompt_integration_limits(
                dataset_config['x_min_integration'],
                dataset_config['x_max_integration']
            )
            dataset_config['x_min_integration'] = x_min
            dataset_config['x_max_integration'] = x_max
            
            # Step 4: Run waterfall analysis (KZ_det_scan mode)
            logger.info("\nStep 4: Running waterfall analysis (KZ_det_scan mode)...")
            # TODO: Implement waterfall_plot call with KZ_det_scan mode
            logger.info("Waterfall analysis would run here with updated parameters")
            
            # Step 5: Prompt for domain fit window
            logger.info("\nStep 5: Adjust domain wall fit window")
            dw_window = self.prompt_domain_fit_window(dataset_config['domain_balance_fit_window'])
            dataset_config['domain_balance_fit_window'] = dw_window
            
            # Step 6: Ask for permission to continue
            print("\n" + "="*80)
            while True:
                response = input("Continue to next dataset? [y/n]: ").strip().lower()
                if response in ['y', 'n']:
                    if response == 'n':
                        logger.info("Analysis stopped by user")
                        return
                    break
            
            dataset_results[dataset_id] = dataset_config
        
        # Save results
        self._save_results(dataset_results)
    
    def _save_results(self, dataset_results):
        """Save all configs and results to iteration folder"""
        logger.info(f"\n{'='*80}")
        logger.info("SAVING RESULTS")
        logger.info(f"{'='*80}\n")
        
        # Save config files
        config_copy = dict(self.config)
        config_copy['datasets'] = list(dataset_results.values())
        
        with open(self.results_dir / 'config.yaml', 'w') as f:
            yaml.dump(config_copy, f, default_flow_style=False)
        logger.info(f"✓ Saved config.yaml")
        
        with open(self.results_dir / 'camera_settings.yaml', 'w') as f:
            yaml.dump(self.camera_settings, f, default_flow_style=False)
        logger.info(f"✓ Saved camera_settings.yaml")
        
        with open(self.results_dir / 'defect_config.yaml', 'w') as f:
            yaml.dump(self.defect_config, f, default_flow_style=False)
        logger.info(f"✓ Saved defect_config.yaml")
        
        # Save analysis metadata
        metadata = {
            'iteration': self.iteration,
            'timestamp': datetime.now().isoformat(),
            'user': getpass.getuser(),
            'num_datasets': len(dataset_results),
            'datasets_analyzed': list(dataset_results.keys()),
        }
        with open(self.results_dir / 'metadata.json', 'w') as f:
            json.dump(metadata, f, indent=2)
        logger.info(f"✓ Saved metadata.json")
        
        logger.info(f"\nAll results saved to: {self.results_dir}")


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Interactive KZ Article Analysis",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Run new analysis
  python run_kz_article_analysis.py config.yaml camera_settings.yaml defect_config.yaml
  
  # Re-run specific iteration
  python run_kz_article_analysis.py config.yaml camera_settings.yaml defect_config.yaml --iteration 3
        """
    )
    
    parser.add_argument('config', help='Path to config.yaml')
    parser.add_argument('camera_settings', help='Path to camera_settings.yaml')
    parser.add_argument('defect_config', help='Path to defect_config.yaml')
    parser.add_argument('--iteration', type=int, default=None, 
                        help='Specific iteration number (default: auto-increment)')
    
    args = parser.parse_args()
    
    # Verify files exist
    for fpath in [args.config, args.camera_settings, args.defect_config]:
        if not os.path.exists(fpath):
            print(f"ERROR: File not found: {fpath}")
            sys.exit(1)
    
    analyzer = KZArticleAnalyzer(
        args.config,
        args.camera_settings,
        args.defect_config,
        iteration=args.iteration
    )
    analyzer.run_analysis()
